version: '3.2'
services:
  start_services:
    image: jwilder/dockerize
    command: "-wait tcp://db:5432 -timeout 30s"
    depends_on:
      - db
  start_applications:
    image: jwilder/dockerize
    command: >
      -wait tcp://cla_public:80
      -wait tcp://cla_frontend:80
      -wait tcp://cla_frontend:8005
      -wait tcp://cla_backend:80
      -wait-retry-interval 2s
      -timeout 180s
    depends_on:
      - cla_public
      - cla_frontend
      - cla_backend

  # services
  db:
    image: postgres:9.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cla_backend

  # applications
  cla_public:
    image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-get-access/laa-cla-public:saids-end-2-end-test-helper-branch.8a43b0e
    ports:
      - target: 80
        published: 5000
        protocol: tcp
        mode: host
    environment:
      HOST_NAME: "0.0.0.0"
      SECRET_KEY: CHANGE_ME
      BACKEND_BASE_URI: http://cla-backend:80
    depends_on:
      - cla_backend
    external_links:
      # Alias the hostname to avoid underscores in domain names, as that causes the following error in cla_backend:
      # "Invalid HTTP_HOST header: 'cla_backend'. The domain name provided is not valid according to RFC 1034/1035"
      - "cla_backend:cla-backend"
  cla_frontend:
    image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-get-access/laa-cla-frontend:master
    ports:
      - target: 80
        published: 8001
        protocol: tcp
        mode: host
      - target: 8005
        published: 8005
        protocol: tcp
        mode: host
    environment:
      ENV: local
      DEBUG: "True"
      SECRET_KEY: CHANGE_ME
      BACKEND_BASE_URI: http://cla-backend:80
      CALL_CENTRE_CLIENT_ID: b4b9220ffcb11ebfdab1
      CALL_CENTRE_SECRET_ID: 2df71313bdd38a2e1b815015e1b14387e7681d41
      CLA_PROVIDER_CLIENT_ID: 59657ed22d980251cdd3
      CALL_PROVIDER_SECRET_ID: 0494287c65bdf61d29f0eeed467ec8e090f0d80f
      SOCKETIO_SERVER_URL: /socket.io
    external_links:
      # Alias the hostname to avoid underscores in domain names, as that causes the following error in cla_backend:
      # "Invalid HTTP_HOST header: 'cla_backend'. The domain name provided is not valid according to RFC 1034/1035"
      - "cla_backend:cla-backend"
    depends_on:
      - cla_backend
  cla_backend:
    image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-get-access/laa-cla-backend:master
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: host
    environment:
      ENV: local
      DEBUG: "True"
      SECRET_KEY: CHANGE_ME
      DB_NAME: cla_backend
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      BACKEND_ENABLED: "True"
      LOAD_TEST_DATA: "True"
      ADMIN_PASSWORD: cla_admin
      ALLOWED_HOSTS: "*"
    depends_on:
      - db

  test_case_handling_system:
    build:
      context: tests/case-handling-system
    environment:
      CLA_FRONTEND_URL: "http://cla_frontend/"
      HEADLESS: "true"

  test_check_legal_aid:
    build:
      context: tests/check-legal-aid
    environment:
      CLA_PUBLIC_URL: http://cla_public
      HEADLESS: "true"
