version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install awscli
          command: |
            sudo pip install awscli
            login="$(aws ecr get-login --region eu-west-1 --no-include-email)"
            ${login}
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            bin/setup && bin/run_tests && bin/stop