version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install awscli
          command: |
            sudo pip install awscli
            login="$(aws ecr get-login --region eu-west-1 --no-include-email)"
            ${login}
      - run:
          name: Build / pull Docker images
          command: |
            docker-compose pull
            docker-compose build
      - run:
          name: Start services and applications
          command: bin/setup
      - run:
          name: Run cucumber tests
          command: bin/run_cucumber_in_docker
          when: always
      - run:
          name: Run javascript tests
          command: bin/run_tests_in_docker
          when: always
      - run:
          name: Clean up running containers
          command: bin/stop
          when: always
workflows:
  version: 2
  run-tests:
    jobs: [build]
  nightly:
    jobs: [build]
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only: [master]
